### PR TITLE
Continuous Integration: Add build configure for Tea CI.

### PR DESCRIPTION
**Pull request by fracting**
Hi,

I added a build configure for winpty, see an example here https://tea-ci.org/fracting/winpty/1

I know you are working on continuous integration on the Appveyor branch, at the same time, I'd like to proposal one more continuous integration with Tea CI, which builds Windows application on Wine ;)

See http://docs.tea-ci.org/usage/overview/ for some introduction.

Please let me know how do you think, thanks!

### CODE REVIEW

**Comment by rprichard** [comment]
Yeah, that seems fine to me.

The `configure` script doesn't have a `--build=` option.  I'm guessing you copied it from [here](https://github.com/Alexpux/MSYS2-packages/blob/dda64a7caa7bee11e63ebd92880010df4e8d5975/winpty-git/PKGBUILD#L60)?  (Maybe it *ought* to have some way to configure the build compiler, but at the moment, it just uses whatever's appropriate according to `uname`.)

Also, the `UNIX_ADAPTER_EXE=winpty.exe` option to `make` is unnecessary now.  The default used to be `console.exe`, but I changed it to `winpty.exe` to match MSYS2.

Could you remove those two things?

Thanks!

**Comment by fracting** [comment]
Thanks for the quick response.

Yes, the configure command line is copied from Msys2.
Ok, I'll remove those two options.

BTW, is there a simplest winpty command line you can suggest to be used as a regression test?
No need to be a full test suite, just some simple task which verifies the latest build starts correctly and basic functional works correctly.

I'm thinking of something like 
```
$ winpty cmd /c ver

Microsoft Windows 5.1.2600 (1.9.11)
```

If there is anyway to `grep` or verify the output, that would be even better. If no, I think it is still better than none.

Thanks!

**Comment by rprichard** [comment]
The best thing I have right now is:

```
make tests
build/trivial_test.exe
```

It should exit successfully (i.e. 0).  The packaging scripts, `ship/ship.py`, builds and runs that test program for every configuration.

**Comment by fracting** [comment]
Ok, it seems this works:
```
$ mintty --log - --exec build/winpty.exe cmd /c ver | grep Windows
Microsoft Windows 5.2.3790 (1.9.10)
```

Could you have a look at my latest patch?
See https://tea-ci.org/fracting/winpty/5 for build result.

If you want to add more test I will do that, or you can do that by yourself as well ;)

**Comment by fracting** [comment]
> make tests

Ah I miss this update, will try right now, please don't merge, thanks.

**Comment by rprichard** [comment]
I didn't know about the `mintty --log` option.  Neat.

I recently added some undocumented switches to `winpty.exe` that might also be useful for testing.  They let you do things like this, for example:
```
rprichard@VBWIN7 ~/proj/winpty
$ build/winpty -Xallow-non-tty -Xplain printf '123\n456' | od -tx1
0000000 31 32 33 0d 0a 34 35 36
0000010
```
`-Xplain` configures winpty to never output escape sequences, which is sometimes useful for programs that embed winpty.

If you want to try adding something like that, that's cool.  It should definitely run `trivial_test.exe`, though.

**Comment by fracting** [comment]
How about version 	22b42e2? In this version, both trivial_test.exe and mintty.exe are used to do a trivial test, in the mintty way, we can read the result from console output in case something wrong happen.

Nice work on `-Xplain`, ideally I think test cases related to `-Xplain` could be implemented as a builtin test suite, so we can share the same test suite between Appveyor CI and Tea CI as well as manually executing the test suite, which could be put in another patch actually, what do you think?

To be honest I'm not going too far for more test cases right now, but in the future if I run into any bugs I'll definitely consider contribute test cases to prevent similar bugs ;)

**Comment by rprichard** [comment]
This commit looks good.  I'll merge it.

> Nice work on -Xplain, ideally I think test cases related to -Xplain could be implemented as a builtin test suite, so we can share the same test suite between Appveyor CI and Tea CI as well as manually executing the test suite, which could be put in another patch actually, what do you think?

Yeah, that makes sense.

Thanks.

**Comment by fracting** [comment]
Thanks, would you please register on https://tea-ci.org by connecting your github account to Tea CI, and click the "ACTIVATE NOW" button on https://tea-ci.org/rprichard/winpty?

Tea CI will ask for read-only access for github api, as well as "write webhook" access, but not ask for sensitive access like write source code.

**Comment by rprichard** [comment]
Ok, I activated it, and I added a tea-ci badge to the README.

**Comment by fracting** [comment]
Nice, thanks!

**Pull request merged**
